PyPoet/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^submit$', views.submit, name="submit"),
    url(r'leaving', views.leaving, name="leaving"),
    url(r'update', views.update, name="update"),
]

PyPoetWeb/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('PyPoet.urls', namespace="PyPoet")),
]

PyPoet/models.py
# from django.db import models
#
# # Create your models here.
# class Prompt(models.Model):
#     url_text = models.CharField(max_length=200)
#     start_index_text = models.CharField(max_length=200)
#     total_lines_text = models.CharField(max_length=200)
#     target_sentence_length_text = models.CharField(max_length=200)
#     sentence_length_threshold = models.CharField(max_length=200)
#     result_text = models.TextField()
#
#     def __str__(self):
#         return self.prompt_text

PyPoet/views.py
from django.views import generic
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import celery.task.control
from celery.result import ResultSet
from . import tasks

results = ResultSet([])

# Create your views here.
class IndexView(generic.TemplateView):
    template_name = 'PyPoet/index.html'

# def submit(request):
#     if not request.method == 'GET':
#         cl = 0
#         p = ""
#         lines = {}
#         url = request.POST["URL"]
#         si = request.POST["StartIndex"]
#         tl = request.POST["TotalLines"]
#         sl = request.POST["SentenceLength"]
#         st = request.POST["SentenceThreshold"]
#         if "CurrentLine" in request.POST and request.POST["CurrentLine"] != "":
#             cl = request.POST["CurrentLine"]
#             cl = int(cl)
#             p = request.POST["Progress"]
#         if int(tl) - cl == 1:
#             print("\n\nADDING ONE")
#             print("Current Line: " + str(cl) + "\n\n")
#             lines = poemAdd(url, si, sl, st, cl, p, False)
#         else:
#             lines = poemAdd(url, si, sl, st, cl, p, True)
#         return render(request, "PyPoet/index.html",
#                       {"output": lines["output"],
#                        "cl" : lines["cl"],
#                        "tl" : tl,
#                        "url" : url,
#                        "si" : si,
#                        "sl" : sl,
#                        "st" : st,
#                        })
#     return HttpResponse("Something went terribly wrong.")
#
# def poemAdd(url, si, sl, st, cl, p, twoLines):
#     output = "" # -1 random start index, 2 for 2 lines
#
#     if twoLines:
#         failLimit = 0
#
#         for i in range(failLimit+1):
#             output = tasks.getTwoLines(p, url, si, 2, sl, st)
#             if not "Could not complete" in output:
#                 break
#
#         return {"output" : output, "cl": cl + 2}
#     output = tasks.getOneLine(p, url, si, 1, sl, st)
#     return {"output": output, "cl": cl + 1}

def submit(request):
    stopAll()
    global results
    if not request.method == 'GET':
        url = request.POST["URL"]
        si = request.POST["StartIndex"]
        tl = request.POST["TotalLines"]
        sl = request.POST["SentenceLength"]
        st = request.POST["SentenceThreshold"]
        tl = int(tl)
        for i in range(1, tl, 2):
            results.add(tasks.poemAdd.delay(url, si, sl, st, True))

        if tl % 2 == 1:
            results.add(tasks.poemAdd.delay(url, si, sl, st, False))

        return JsonResponse({'Down to':'business'})
    return HttpResponse("Something went terribly wrong.")

def leaving(request):
    stopAll()
    return JsonResponse({'Good':'bye'})

def update(request):
    global results
    done = results.completed_count()
    total = len(results)
    # progStr = "Progress: " + str(done) + " / " + str(total) + " operations"
    if total == 0:
        progStr = 0
    else:
        progStr = done/total*100
    if results.ready() and total != 0:
        return JsonResponse({'progress':progStr, 'output':results.get()})
    return JsonResponse({'progress':progStr})

def stopAll():
    global results
    results.revoke(terminate=True)
    results.clear()
    celery.task.control.discard_all()

PyPoet/templates/PyPoet/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PyPoet</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'PyPoet/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'PyPoet/css/bootstrap-theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'PyPoet/css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Cormorant" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="page-header">
        <h1>PyPoet</h1>
    </div>
    {% if error_message %}<p>{{ error_message }}</p>{% endif %}
    <form id = "settingsForm"> {% csrf_token %}
        <div class="form-group form-inline">
            <label for="URL_Box">Source URL:</label>
            <input type="text" name="URL" class="form-control" id="URL_Box" data-toggle="tooltip" data-placement="right" title="Should begin with 'http'" value="http://www.textfiles.com/etext/FICTION/80day10.txt">
        </div>
        <div class="form-group form-inline">
            <label for="StartIndexBox">Start index:</label>
            <input type="number" class="form-control" name="StartIndex" id="StartIndexBox" data-toggle="tooltip" data-placement="right" title="Sentence number to start searching for rhymes at (can be used to skip non-text material)" value="0">
        </div>
        <div class="form-group form-inline">
            <label for="TotalLinesBox">Total poem lines:</label>
            <input type="number" class="form-control" name="TotalLines" id="TotalLinesBox" data-toggle="tooltip" data-placement="right" title="Total lines in your final poem" value="6">
        </div>
        <div class="form-group form-inline">
            <label for="SentenceLengthBox">Target sentence length:</label>
            <input type="number" class="form-control" name="SentenceLength" id="SentenceLengthBox" data-toggle="tooltip" data-placement="right" title="Target sentence length of each line of poem" value="5">
        </div>
        <div class="form-group form-inline">
            <label for="SentenceThresholdBox">Sentence length threshold:</label>
            <input type="number" class="form-control" name="SentenceThreshold" id="SentenceThresholdBox" data-toggle="tooltip" data-placement="right" title="Variation allowed from above length" value="10">
        </div>

        <input type="submit" class="btn" id = "submit_button">
    </form>

    <!--<p id = "CurrentLineDisplay">Progress: <i>Pending</i></p>-->
    <div class="progress" style="width:30em">
      <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="0"  aria-valuemin="0" aria-valuemax="100" style="width:3em">
        0%
      </div>
    </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="http://malsup.github.com/jquery.form.js"></script>
<script src="{% static 'PyPoet/js/bootstrap.js' %}"></script>
<script>
    //I dislike inline JS too, but it allows the use of Django Template Language
    $(window).on('beforeunload', function(){
        $.ajax({url:"{% url 'PyPoet:leaving' %}", async:false});
        console.log("Leaving");
    });
    $(document).ready(function(){

        $('[data-toggle="tooltip"]').tooltip();

        setInterval(function(){
            $.get("{% url 'PyPoet:update' %}", function(data){
            console.log(data);
                //$("#CurrentLineDisplay").text(data["progress"]);

                $(".progress-bar").text(Math.round(data["progress"])+"%");
                $(".progress-bar").css('width', data["progress"]+"%");

                if("output" in data){
                    $("#ProgressDisplay").html(data["output"]);
                }
            });
        },
        4000);

        $("#settingsForm").ajaxForm({url: "{% url 'PyPoet:submit' %}", type: 'post'});
    });
</script>

<p id = "ProgressDisplay"></p>

</div

</script>
</body>
</html>

PyPoet/templates/PyPoet/indexOld.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PyPoet</title>
</head>
<body>
<h1>PyPoet</h1>
{% if error_message %}<p>{{ error_message }}</p>{% endif %}
<form action="{% url 'PyPoet:submit' %}"} method="post" id = "settingsForm">
    {% csrf_token %}
    <div class="prompt">
        <label for="URL_Box">Put URL of text here:</label>
        <input type="text" name="URL" id="URL_Box" {% if output %} value = {{ url }}
               {% else %} value="http://www.textfiles.com/etext/FICTION/80day10.txt" {% endif %}>
    </div>
    <div class="prompt">
        <label for="StartIndexBox">Start index (sentence # to start on):</label>
        <input type="number" name="StartIndex" id="StartIndexBox" {% if output %} value = {{ si }}
               {% else %} value="0" {% endif %}>
    </div>
    <div class="prompt">
        <label for="TotalLinesBox">Target # of lines for result poem:</label>
        <input type="number" name="TotalLines" id="TotalLinesBox" {% if output %} value={{ tl }}
               {% else %} value="6" {% endif %}>
    </div>
    <div class="prompt">
        <label for="SentenceLengthBox">Target sentence length for each line of result poem:</label>
        <input type="number" name="SentenceLength" id="SentenceLengthBox" {% if output %} value = {{ sl }}
               {% else %} value="5" {% endif %}>
    </div>
    <div class="prompt">
        <label for="SentenceThresholdBox">Threshold for target sentence length (allowed variation):</label>
        <input type="number" name="SentenceThreshold" id="SentenceThresholdBox" {% if output %} value = {{ st }}
               {% else %} value="10" {% endif %}>
    </div>

    {% if output %}
    <input type="hidden" name="CurrentLine" id = "CurrentLineBox" value = "{{ cl }}"></input>
    <input type="hidden" name="Progress" id = "ProgressBox" value = "{{ output }}"></input>
    {% endif %}

    <input type="submit" id = "submit_button">
</form>

<p id = "CurrentLineDisplay">Progress: 0%</p>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script>
    $(window).on('beforeunload', function(){
        $.ajax({url:"{% url 'PyPoet:leaving' %}", async:false});
        console.log("Leaving");
    });
    $(document).ready(function(){
        setInterval(function(){
            console.log("Running get");
            $.get("{% url 'PyPoet:update' %}", function(data){
            console.log(data);
                $("#CurrentLineDisplay").text("Progress: " + data["progress"]);
            });
        },
        2000);
    });
</script>

{% if output %}
<h2>Result</h2>
<p id = "ProgressDisplay">{% autoescape off %} {{ output }} {% endautoescape %}</p>

<!--<script>-->
<!--window.onload = function(){-->
    <!--settings = document.getElementById("settingsForm");-->
    <!--sub_button = document.getElementById("submit_button");-->

    <!--settings.onsubmit = function(){-->
        <!--if( {{ cl }} > 0 ){-->
            <!--document.getElementById("CurrentLineBox").value = "";-->
            <!--document.getElementById("ProgressBox").value = "";-->
            <!--document.getElementById("CurrentLineDisplay").innerHTML = "";-->
            <!--document.getElementById("ProgressDisplay").innerHTML = "";-->
        <!--}-->
    <!--}-->

    <!--if( {{ cl }} < {{ tl }} ){ //Mixed template language and JS ftw-->
        <!--settings.submit();-->
    <!--}-->
    <!--else{-->
        <!--document.getElementById("CurrentLineDisplay").innerHTML = "Done!";-->
    <!--}-->
<!--}-->
</script>
{% endif %}
</body>
</html>